#include "spg/integrated_mpc/HumanoidObstacleAvoidanceMPC.hpp"
#include <cmath>
#include <iostream>
#include <algorithm>

// Include acados C interface
#ifdef HAVE_ACADOS
extern "C" {
#include "acados/utils/types.h"
#include "acados/utils/print.h"
#include "acados_c/ocp_nlp_interface.h"

// Generated by acados_template for obstacle avoidance MPC
// NOTE: You need to generate this with generate_acados_obstacle_mpc.py
#include "robot_obstacle_mpc_model/robot_obstacle_mpc_model.h"
#include "acados_solver_robot_obstacle_mpc.h"
}
#endif

namespace spg {
namespace integrated_mpc {

// ==================== ObstacleAvoidanceMPCParams ====================

ObstacleAvoidanceMPCParams::ObstacleAvoidanceMPCParams()
    : dt(0.15)
    , horizon(20)
    , vx_max(0.8)
    , vy_max(0.3)
    , omega_max(1.2)
    , ax_max(4.0)
    , ay_max(3.0)
    , alpha_max(2.0)
    , max_obstacles(10)
    , robot_radius(0.3)
    , obstacle_margin(0.2)
    , collision_weight(1000.0)
    , Q_pos(15.0)
    , Q_theta(2.0)
    , Q_vel(0.5)
    , R_accel(0.1)
    , Q_term_pos(100.0)
    , Q_term_theta(10.0)
    , Q_term_vel(5.0)
{}

// ==================== Utility Functions ====================

double HumanoidObstacleAvoidanceMPC::wrap_pi(double a) {
    while (a <= -M_PI) a += 2.0 * M_PI;
    while (a >   M_PI) a -= 2.0 * M_PI;
    return a;
}

double HumanoidObstacleAvoidanceMPC::clamp(double v, double lo, double hi) {
    return std::max(lo, std::min(hi, v));
}

// ==================== HumanoidObstacleAvoidanceMPC Implementation ====================

HumanoidObstacleAvoidanceMPC::HumanoidObstacleAvoidanceMPC(const ObstacleAvoidanceMPCParams& params)
    : params_(params)
    , capsule_(nullptr)
    , solver_initialized_(false)
    , has_previous_solution_(false)
{
#ifdef HAVE_ACADOS
    // Create acados solver capsule
    capsule_ = robot_obstacle_mpc_acados_create_capsule();
    if (!capsule_) {
        std::cerr << "HumanoidObstacleAvoidanceMPC: Failed to create acados capsule\n";
        std::cerr << "  Make sure you've generated the solver with generate_acados_obstacle_mpc.py\n";
        return;
    }
    
    // Create solver (allocate and initialize)
    int status = robot_obstacle_mpc_acados_create(capsule_);
    if (status != 0) {
        std::cerr << "HumanoidObstacleAvoidanceMPC: acados_create failed with status " << status << "\n";
        robot_obstacle_mpc_acados_free_capsule(capsule_);
        capsule_ = nullptr;
        return;
    }
    
    solver_initialized_ = true;
    std::cout << "HumanoidObstacleAvoidanceMPC: Acados solver initialized successfully.\n";
    std::cout << "  dt=" << params_.dt << ", N=" << params_.horizon << "\n";
    std::cout << "  Max obstacles: " << params_.max_obstacles << "\n";
    std::cout << "  Robot radius: " << params_.robot_radius << " m\n";
    std::cout << "  Obstacle margin: " << params_.obstacle_margin << " m\n";
    
    // Initialize solver with zeros for first solve
    for (int k = 0; k <= params_.horizon; ++k) {
        double x_init[6] = {0, 0, 0, 0, 0, 0};
        ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                        capsule_->nlp_in, k, "x", x_init);
    }
    for (int k = 0; k < params_.horizon; ++k) {
        double u_init[3] = {0, 0, 0};
        ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                        capsule_->nlp_in, k, "u", u_init);
    }
#else
    std::cerr << "HumanoidObstacleAvoidanceMPC: Built without acados support (HAVE_ACADOS not defined)\n";
#endif
}

HumanoidObstacleAvoidanceMPC::~HumanoidObstacleAvoidanceMPC() {
#ifdef HAVE_ACADOS
    if (capsule_) {
        robot_obstacle_mpc_acados_free(capsule_);
        robot_obstacle_mpc_acados_free_capsule(capsule_);
    }
#endif
}

bool HumanoidObstacleAvoidanceMPC::computeControl(
    const ObstacleAvoidanceState& x0,
    const ObstacleAvoidanceState& x_goal,
    const std::vector<Obstacle>& obstacles,
    ObstacleAvoidanceControl& u_out)
{
    if (!solver_initialized_) {
        std::cerr << "HumanoidObstacleAvoidanceMPC: Solver not initialized\n";
        return false;
    }
    
#ifdef HAVE_ACADOS
    // Set initial state constraint
    setInitialState(x0);
    
    // Set goal reference
    setGoalReference(x_goal);
    
    // Update obstacle avoidance constraints
    updateObstacleConstraints(obstacles);
    
    // Apply warm-start (shift previous solution)
    applyWarmStart();
    
    // Solve
    int status = robot_obstacle_mpc_acados_solve(capsule_);
    if (status != 0) {
        std::cerr << "HumanoidObstacleAvoidanceMPC: Solve failed with status " << status << "\n";
        // Even if solver fails, try to extract best solution so far
    }
    
    // Store solution for next warm-start
    storeSolution();
    
    // Extract first control (acceleration)
    u_out = getFirstControl();
    
    // Debug: print what MPC computed
    static int debug_ctr = 0;
    if (debug_ctr++ % 50 == 0) {
        ObstacleAvoidanceVelocity v = getVelocityCommand();
        double dx = x_goal.px - x0.px;
        double dy = x_goal.py - x0.py;
        double dist_to_goal = std::hypot(dx, dy);
        
        std::cout << "Integrated MPC output:\n";
        std::cout << "  Current: pos=(" << x0.px << "," << x0.py << ") theta=" << x0.theta << "\n";
        std::cout << "  Goal: pos=(" << x_goal.px << "," << x_goal.py << ") dist=" << dist_to_goal << "m\n";
        std::cout << "  Obstacles: " << obstacles.size() << " active\n";
        std::cout << "  Velocity cmd: vx=" << v.vx << " vy=" << v.vy << " omega=" << v.omega << "\n";
        std::cout << "  Accel cmd: ax=" << u_out.ax << " ay=" << u_out.ay << " alpha=" << u_out.alpha << "\n";
    }
    
    return (status == 0);
#else
    (void)x0; (void)x_goal; (void)obstacles; (void)u_out;
    return false;
#endif
}

bool HumanoidObstacleAvoidanceMPC::computeControlAndTrajectory(
    const ObstacleAvoidanceState& x0,
    const ObstacleAvoidanceState& x_goal,
    const std::vector<Obstacle>& obstacles,
    ObstacleAvoidanceControl& u_out,
    std::vector<ObstacleAvoidanceState>& predicted_states,
    std::vector<ObstacleAvoidanceControl>& predicted_controls)
{
    if (!computeControl(x0, x_goal, obstacles, u_out)) {
        return false;
    }
    
    // Get predicted trajectory
    getPredictedTrajectory(predicted_states, predicted_controls);
    
    return true;
}

void HumanoidObstacleAvoidanceMPC::setInitialState(const ObstacleAvoidanceState& x0) {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    double x0_arr[6] = {x0.px, x0.py, x0.theta, x0.vx, x0.vy, x0.omega};
    ocp_nlp_constraints_model_set(capsule_->nlp_config, capsule_->nlp_dims, 
                                   capsule_->nlp_in, capsule_->nlp_out, 0, "lbx", x0_arr);
    ocp_nlp_constraints_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                                   capsule_->nlp_in, capsule_->nlp_out, 0, "ubx", x0_arr);
#else
    (void)x0;
#endif
}

void HumanoidObstacleAvoidanceMPC::setGoalReference(const ObstacleAvoidanceState& x_goal) {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    // DEBUG: Print what we're setting as goal
    std::cout << "setGoalReference: target=(" << x_goal.px << "," << x_goal.py 
              << "," << x_goal.theta << ")" << std::endl;


    // Goal state (with zero velocities)
    double goal_state[6] = {
        x_goal.px,
        x_goal.py,
        x_goal.theta,
        0.0,  // zero velocity at goal
        0.0,
        0.0
    };
    
    // Set same goal for all stages
    for (int k = 0; k < params_.horizon; ++k) {
        double yref[9];  // [px, py, theta, vx, vy, omega, ax, ay, alpha]
        yref[0] = goal_state[0];
        yref[1] = goal_state[1];
        yref[2] = goal_state[2];
        yref[3] = goal_state[3];
        yref[4] = goal_state[4];
        yref[5] = goal_state[5];
        yref[6] = 0.0;  // zero acceleration reference
        yref[7] = 0.0;
        yref[8] = 0.0;
        
        ocp_nlp_cost_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                               capsule_->nlp_in, k, "yref", yref);
        std::cout << "  Stage " << k << " yref set to: [" << yref[0] << "," << yref[1] << "," << yref[2] << "]" << std::endl;
    }
    
    // Terminal reference
    ocp_nlp_cost_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                           capsule_->nlp_in, params_.horizon, "yref", goal_state);
#else
    (void)x_goal;
#endif
}

void HumanoidObstacleAvoidanceMPC::updateObstacleConstraints(const std::vector<Obstacle>& obstacles) {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    // Update obstacle parameters for each stage
    // This assumes the acados model has parameters for obstacle positions/radii
    // Format: [obs1_px, obs1_py, obs1_r, obs2_px, obs2_py, obs2_r, ...]
    
    const int n_obs = std::min(static_cast<int>(obstacles.size()), params_.max_obstacles);
    const int param_size = params_.max_obstacles * 3;  // 3 params per obstacle (px, py, r)
    
    std::vector<double> obs_params(param_size, 0.0);  // zero raduis = inactive obstacle
    
    // Pack active obstacles
    for (int i = 0; i < n_obs; ++i) {
        if (obstacles[i].active) {
            obs_params[i * 3 + 0] = obstacles[i].px;
            obs_params[i * 3 + 1] = obstacles[i].py;
            obs_params[i * 3 + 2] = obstacles[i].radius + params_.robot_radius + params_.obstacle_margin;
        }
    }
    
    // Set parameters for all stages using the correct acados API
    // Parameters are set through ocp_nlp_in, not through constraints
    for (int k = 0; k <= params_.horizon; ++k) {
        robot_obstacle_mpc_acados_update_params(capsule_, k, obs_params.data(), param_size);
    }
#else
    (void)obstacles;
#endif
}

ObstacleAvoidanceControl HumanoidObstacleAvoidanceMPC::getFirstControl() const {
    ObstacleAvoidanceControl control{0.0, 0.0, 0.0};
    
#ifdef HAVE_ACADOS
    if (!capsule_) return control;
    
    double u0[3];
    ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                    capsule_->nlp_out, 0, "u", u0);
    
    control.ax = u0[0];
    control.ay = u0[1];
    control.alpha = u0[2];
#endif
    
    return control;
}

void HumanoidObstacleAvoidanceMPC::getPredictedTrajectory(
    std::vector<ObstacleAvoidanceState>& states,
    std::vector<ObstacleAvoidanceControl>& controls) const
{
    states.resize(params_.horizon + 1);
    controls.resize(params_.horizon);
    
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    // Extract states
    for (int k = 0; k <= params_.horizon; ++k) {
        double x[6];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, k, "x", x);
        
        states[k].px = x[0];
        states[k].py = x[1];
        states[k].theta = x[2];
        states[k].vx = x[3];
        states[k].vy = x[4];
        states[k].omega = x[5];
    }
    
    // Extract controls
    for (int k = 0; k < params_.horizon; ++k) {
        double u[3];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, k, "u", u);
        
        controls[k].ax = u[0];
        controls[k].ay = u[1];
        controls[k].alpha = u[2];
    }
#endif
}

ObstacleAvoidanceVelocity HumanoidObstacleAvoidanceMPC::getVelocityCommand() const {
    ObstacleAvoidanceVelocity vel{0.0, 0.0, 0.0};
    
#ifdef HAVE_ACADOS
    if (!capsule_) return vel;
    
    // Get next predicted state (after applying first control)
    double x1[6];
    ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                    capsule_->nlp_out, 1, "x", x1);
    
    vel.vx = x1[3];
    vel.vy = x1[4];
    vel.omega = x1[5];
#endif
    
    return vel;
}

void HumanoidObstacleAvoidanceMPC::applyWarmStart() {
#ifdef HAVE_ACADOS
    if (!capsule_ || !has_previous_solution_) return;
    
    const int N = params_.horizon;
    
    // Shift states: x_k^(0) = x_{k+1}^{*,prev}
    for (int i = 0; i < N; ++i) {
        ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                        capsule_->nlp_in, i, "x", prev_states_[i + 1].data());
    }
    
    // Extrapolate final state
    double final_state[6];
    for (int j = 0; j < 6; ++j) {
        final_state[j] = prev_states_[N][j];
    }
    
    const double theta_N = final_state[2];
    const double vx_N = final_state[3];
    const double vy_N = final_state[4];
    const double omega_N = final_state[5];
    
    final_state[0] += params_.dt * (std::cos(theta_N) * vx_N - std::sin(theta_N) * vy_N);
    final_state[1] += params_.dt * (std::sin(theta_N) * vx_N + std::cos(theta_N) * vy_N);
    final_state[2] = wrap_pi(final_state[2] + params_.dt * omega_N);
    
    ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                    capsule_->nlp_in, N, "x", final_state);
    
    // Shift controls
    for (int i = 0; i < N - 1; ++i) {
        ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                        capsule_->nlp_in, i, "u", prev_controls_[i + 1].data());
    }
    
    double zero_control[3] = {0.0, 0.0, 0.0};
    ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                    capsule_->nlp_in, N - 1, "u", zero_control);
#endif
}

void HumanoidObstacleAvoidanceMPC::storeSolution() {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    const int N = params_.horizon;
    prev_states_.resize(N + 1);
    prev_controls_.resize(N);
    
    for (int i = 0; i <= N; ++i) {
        double x[6];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, i, "x", x);
        prev_states_[i] = {x[0], x[1], x[2], x[3], x[4], x[5]};
    }
    
    for (int i = 0; i < N; ++i) {
        double u[3];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, i, "u", u);
        prev_controls_[i] = {u[0], u[1], u[2]};
    }
    
    has_previous_solution_ = true;
#endif
}

} // namespace integrated_mpc
} // namespace spg
