#include "spg/setpoint/HumanoidReferencePredictedTrajMPC.hpp"
#include <cmath>
#include <iostream>
#include <algorithm>

// Include acados C interface
#ifdef HAVE_ACADOS
extern "C" {
#include "acados/utils/types.h"
#include "acados/utils/print.h"
#include "acados_c/ocp_nlp_interface.h"

// Generated by acados_template (replace with your actual generated names)
#include "robot_mpc_predicted_traj_model/robot_mpc_predicted_traj_model.h"
#include "acados_solver_robot_mpc_predicted_traj.h"
}
#endif

namespace spg {
namespace setpoint {

// ==================== AcadosMPCParams ====================

AcadosMPCParamsPredictedTraj::AcadosMPCParamsPredictedTraj()
    : dt(0.4)
    , horizon(20)
    , vx_max(0.8)
    , vy_max(0.3)
    , omega_max(1.2)
    , ax_max(4.0)
    , ay_max(3.0)
    , alpha_max(2.0)
    , polygon_sides(12)
{}

// ==================== Utility Functions ====================

double HumanoidReferencePredictedTrajMPC::wrap_pi(double a) {
    while (a <= -M_PI) a += 2.0 * M_PI;
    while (a >   M_PI) a -= 2.0 * M_PI;
    return a;
}

double HumanoidReferencePredictedTrajMPC::clamp(double v, double lo, double hi) {
    return std::max(lo, std::min(hi, v));
}

// ==================== HumanoidReferencePredictedTrajMPC Implementation ====================

HumanoidReferencePredictedTrajMPC::HumanoidReferencePredictedTrajMPC(const AcadosMPCParamsPredictedTraj& params)
    : params_(params)
    , capsule_(nullptr)
    , solver_initialized_(false)
    , has_previous_solution_(false)
{
#ifdef HAVE_ACADOS
    // Create acados solver capsule
    capsule_ = robot_mpc_predicted_traj_acados_create_capsule();
    if (!capsule_) {
        std::cerr << "HumanoidReferencePredictedTrajMPC: Failed to create acados capsule\n";
        return;
    }
    
    // Create solver (allocate and initialize)
    int status = robot_mpc_predicted_traj_acados_create(capsule_);
    if (status != 0) {
        std::cerr << "HumanoidReferencePredictedTrajMPC: acados_create failed with status " << status << "\n";
        robot_mpc_predicted_traj_acados_free_capsule(capsule_);
        capsule_ = nullptr;
        return;
    }
    
    solver_initialized_ = true;
    std::cout << "HumanoidReferencePredictedTrajMPC: Acados solver initialized successfully.\n";
    std::cout << "  dt=" << params_.dt << ", N=" << params_.horizon << "\n";
#else
    std::cerr << "HumanoidReferencePredictedTrajMPC: Built without acados support (HAVE_ACADOS not defined)\n";
#endif
}

HumanoidReferencePredictedTrajMPC::~HumanoidReferencePredictedTrajMPC() {
#ifdef HAVE_ACADOS
    if (capsule_) {
        robot_mpc_predicted_traj_acados_free(capsule_);
        robot_mpc_predicted_traj_acados_free_capsule(capsule_);
    }
#endif
}

bool HumanoidReferencePredictedTrajMPC::computeControl(
    const AcadosMPCStatePredictedTraj& x0,
    const AcadosMPCStatePredictedTraj& x_goal,
    AcadosMPCControlPredictedTraj& u_out)
{
    if (!solver_initialized_) {
        std::cerr << "HumanoidReferencePredictedTrajMPC: Solver not initialized\n";
        return false;
    }
    
#ifdef HAVE_ACADOS
    // Build reference trajectory (fixed goal for all stages)
    AcadosMPCReferencePredictedTraj ref = buildReference(x0, x_goal);
    
    // Set initial state constraint
    setInitialState(x0);
    
    // Set stage and terminal references
    setReferences(ref);
    
    // Apply warm-start (shift previous solution)
    applyWarmStart();
    
    // Solve
    int status = robot_mpc_predicted_traj_acados_solve(capsule_);
    if (status != 0) {
        std::cerr << "HumanoidReferencePredictedTrajMPC: Solve failed with status " << status << "\n";
        return false;
    }
    
    // Store solution for next warm-start
    storeSolution();
    
    // Extract first control (acceleration)
    u_out = getFirstControl();
    
    // Debug: print what MPC computed
    static int debug_ctr = 0;
    if (debug_ctr++ % 50 == 0) {
        AcadosMPCVelocityPredictedTraj v = getVelocityCommand();
        std::cout << "MPC output: vel=(" << v.vx << "," << v.vy << "," << v.omega 
                  << ") acc=(" << u_out.ax << "," << u_out.ay << "," << u_out.alpha << ")\n";
        std::cout << "  Ref[0]: pos=(" << ref.x_ref[0][0] << "," << ref.x_ref[0][1] << ") acc=(" 
                  << ref.u_ref[0][0] << "," << ref.u_ref[0][1] << ")\n";
        std::cout << "  x0: pos=(" << x0.px << "," << x0.py << ") vel=(" << x0.vx << "," << x0.vy << ")\n";
    }
    
    return true;
#else
    (void)x0; (void)x_goal; (void)u_out;
    return false;
#endif
}

bool HumanoidReferencePredictedTrajMPC::computeControlAndTrajectory(
    const AcadosMPCStatePredictedTraj& x0,
    const AcadosMPCStatePredictedTraj& x_goal,
    AcadosMPCControlPredictedTraj& u_out,
    std::vector<AcadosMPCStatePredictedTraj>& predicted_states,
    std::vector<AcadosMPCControlPredictedTraj>& predicted_controls)
{
    if (!computeControl(x0, x_goal, u_out)) {
        return false;
    }
    
    // Get predicted trajectory
    getPredictedTrajectory(predicted_states, predicted_controls);
    
    return true;
}

AcadosMPCReferencePredictedTraj HumanoidReferencePredictedTrajMPC::buildReference(
    const AcadosMPCStatePredictedTraj& x0,
    const AcadosMPCStatePredictedTraj& x_goal) const
{
    AcadosMPCReferencePredictedTraj ref;
    ref.x_ref.resize(params_.horizon + 1);
    ref.u_ref.resize(params_.horizon);

    const double dx = x_goal.px - x0.px;
    const double dy = x_goal.py - x0.py;
    const double dist = std::hypot(dx, dy);
    const double angle_to_goal = std::atan2(dy, dx);
    const double ref_theta = (dist > 2.0) ? angle_to_goal : x_goal.theta;
    
    // FIXED GOAL REFERENCE: Use same goal for all stages k=0,...,N
    // Goal is in WORLD FRAME with zero velocities
    std::array<double, 6> goal_state = {
        x_goal.px,     // Position x (world frame)
        x_goal.py,     // Position y (world frame)
        ref_theta,     // Heading (world frame)
        0.0,           // Forward velocity = 0 at goal
        0.0,           // Sideways velocity = 0 at goal
        0.0            // Angular velocity = 0 at goal
    };
    
    // Set same goal for ALL stages (not a time-varying trajectory)
    for (int k = 0; k <= params_.horizon; ++k) {
        ref.x_ref[k] = goal_state;
    }
    
    // Zero control reference (accelerations)
    std::array<double, 3> zero_control = {0.0, 0.0, 0.0};
    for (int k = 0; k < params_.horizon; ++k) {
        ref.u_ref[k] = zero_control;
    }
    
    // Debug: print dynamic heading reference
    static int ref_debug = 0;
    if (ref_debug++ % 50 == 0) {
        std::cout << "buildReference: goal=(" << x_goal.px << "," << x_goal.py 
                  << "," << x_goal.theta << ") dist=" << dist << "m"
                  << " ref_theta=" << ref_theta << " (tracking " 
                  << (dist > 2.0 ? "angle_to_goal" : "goal_theta") << ")\n";
    }
    
    return ref;
}

void HumanoidReferencePredictedTrajMPC::setInitialState(const AcadosMPCStatePredictedTraj& x0) {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    double x0_arr[6] = {x0.px, x0.py, x0.theta, x0.vx, x0.vy, x0.omega};
    ocp_nlp_constraints_model_set(capsule_->nlp_config, capsule_->nlp_dims, 
                                   capsule_->nlp_in, capsule_->nlp_out, 0, "lbx", x0_arr);
    ocp_nlp_constraints_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                                   capsule_->nlp_in, capsule_->nlp_out, 0, "ubx", x0_arr);
#else
    (void)x0;
#endif
}

void HumanoidReferencePredictedTrajMPC::setReferences(const AcadosMPCReferencePredictedTraj& ref) {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    // Assuming LINEAR_LS cost with yref = [x; u] at stages and yref_e = [x] at terminal
    
    // Stage references
    for (int k = 0; k < params_.horizon; ++k) {
        double yref[9];  // [px, py, theta, vx, vy, omega, ax, ay, alpha]
        yref[0] = ref.x_ref[k][0];
        yref[1] = ref.x_ref[k][1];
        yref[2] = ref.x_ref[k][2];
        yref[3] = ref.x_ref[k][3];
        yref[4] = ref.x_ref[k][4];
        yref[5] = ref.x_ref[k][5];
        yref[6] = ref.u_ref[k][0];
        yref[7] = ref.u_ref[k][1];
        yref[8] = ref.u_ref[k][2];
        
        ocp_nlp_cost_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                               capsule_->nlp_in, k, "yref", yref);
    }
    
    // Terminal reference
    double yref_e[6];  // [px, py, theta, vx, vy, omega]
    yref_e[0] = ref.x_ref[params_.horizon][0];
    yref_e[1] = ref.x_ref[params_.horizon][1];
    yref_e[2] = ref.x_ref[params_.horizon][2];
    yref_e[3] = ref.x_ref[params_.horizon][3];
    yref_e[4] = ref.x_ref[params_.horizon][4];
    yref_e[5] = ref.x_ref[params_.horizon][5];
    
    ocp_nlp_cost_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                           capsule_->nlp_in, params_.horizon, "yref", yref_e);
#else
    (void)ref;
#endif
}

AcadosMPCControlPredictedTraj HumanoidReferencePredictedTrajMPC::getFirstControl() const {
    AcadosMPCControlPredictedTraj control{0.0, 0.0, 0.0};
    
#ifdef HAVE_ACADOS
    if (!capsule_) return control;
    
    double u0[3];
    ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                    capsule_->nlp_out, 0, "u", u0);
    
    control.ax = u0[0];
    control.ay = u0[1];
    control.alpha = u0[2];
#endif
    
    return control;
}

void HumanoidReferencePredictedTrajMPC::getPredictedTrajectory(
    std::vector<AcadosMPCStatePredictedTraj>& states,
    std::vector<AcadosMPCControlPredictedTraj>& controls) const
{
    states.resize(params_.horizon + 1);
    controls.resize(params_.horizon);
    
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    // Extract states
    for (int k = 0; k <= params_.horizon; ++k) {
        double x[6];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, k, "x", x);
        
        states[k].px = x[0];
        states[k].py = x[1];
        states[k].theta = x[2];
        states[k].vx = x[3];
        states[k].vy = x[4];
        states[k].omega = x[5];
    }
    
    // Extract controls
    for (int k = 0; k < params_.horizon; ++k) {
        double u[3];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, k, "u", u);
        
        controls[k].ax = u[0];
        controls[k].ay = u[1];
        controls[k].alpha = u[2];
    }
#endif
}

AcadosMPCVelocityPredictedTraj HumanoidReferencePredictedTrajMPC::getVelocityCommand() const {
    AcadosMPCVelocityPredictedTraj vel{0.0, 0.0, 0.0};
    
#ifdef HAVE_ACADOS
    if (!capsule_) return vel;
    
    // Get NEXT predicted state (after applying first control)
    // State 0 is the constrained initial state, state 1 is after integration
    double x1[6];
    ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                    capsule_->nlp_out, 1, "x", x1);
    
    vel.vx = x1[3];
    vel.vy = x1[4];
    vel.omega = x1[5];
#endif
    
    return vel;
}

void HumanoidReferencePredictedTrajMPC::applyWarmStart() {
#ifdef HAVE_ACADOS
    if (!capsule_ || !has_previous_solution_) return;
    
    const int N = params_.horizon;
    
    // Shift states: x_k^(0) = x_{k+1}^{*,prev}
    for (int i = 0; i < N; ++i) {
        ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                        capsule_->nlp_in, i, "x", prev_states_[i + 1].data());
    }
    
    // Extrapolate final state: x_N = x_N^{prev} + dt*f(x_N^{prev}, 0)
    // Simple forward Euler with zero control
    double final_state[6];
    for (int j = 0; j < 6; ++j) {
        final_state[j] = prev_states_[N][j];
    }
    
    // Position dynamics: px_dot = cos(theta)*vx - sin(theta)*vy
    const double theta_N = final_state[2];
    const double vx_N = final_state[3];
    const double vy_N = final_state[4];
    const double omega_N = final_state[5];
    
    final_state[0] += params_.dt * (std::cos(theta_N) * vx_N - std::sin(theta_N) * vy_N);
    final_state[1] += params_.dt * (std::sin(theta_N) * vx_N + std::cos(theta_N) * vy_N);
    final_state[2] = wrap_pi(final_state[2] + params_.dt * omega_N);
    // Velocities unchanged with zero acceleration
    
    ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                    capsule_->nlp_in, N, "x", final_state);
    
    // Shift controls: u_k^(0) = u_{k+1}^{*,prev}
    for (int i = 0; i < N - 1; ++i) {
        ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                        capsule_->nlp_in, i, "u", prev_controls_[i + 1].data());
    }
    
    // Append zero control at final stage
    double zero_control[3] = {0.0, 0.0, 0.0};
    ocp_nlp_out_set(capsule_->nlp_config, capsule_->nlp_dims, capsule_->nlp_out,
                    capsule_->nlp_in, N - 1, "u", zero_control);
#endif
}

void HumanoidReferencePredictedTrajMPC::storeSolution() {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    const int N = params_.horizon;
    prev_states_.resize(N + 1);
    prev_controls_.resize(N);
    
    // Store all states
    for (int i = 0; i <= N; ++i) {
        double x[6];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, i, "x", x);
        prev_states_[i] = {x[0], x[1], x[2], x[3], x[4], x[5]};
    }
    
    // Store all controls
    for (int i = 0; i < N; ++i) {
        double u[3];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, i, "u", u);
        prev_controls_[i] = {u[0], u[1], u[2]};
    }
    
    has_previous_solution_ = true;
#endif
}

} // namespace setpoint
} // namespace spg
