#include "spg/setpoint/HumanoidReferenceMPC.hpp"
#include <cmath>
#include <iostream>
#include <algorithm>

// Include acados C interface
#ifdef HAVE_ACADOS
extern "C" {
#include "acados/utils/types.h"
#include "acados/utils/print.h"
#include "acados_c/ocp_nlp_interface.h"

// Generated by acados_template (replace with your actual generated names)
#include "robot_mpc_model/robot_mpc_model.h"
#include "acados_solver_robot_mpc.h"
}
#endif

namespace spg {
namespace setpoint {

// ==================== AcadosMPCParams ====================

AcadosMPCParams::AcadosMPCParams()
    : dt(0.05)
    , horizon(20)
    , vx_max(0.8)
    , vy_max(0.3)
    , omega_max(1.2)
    , ax_max(4.0)
    , ay_max(3.0)
    , alpha_max(2.0)
    , polygon_sides(12)
{}

// ==================== Utility Functions ====================

double HumanoidReferenceMPC::wrap_pi(double a) {
    while (a <= -M_PI) a += 2.0 * M_PI;
    while (a >   M_PI) a -= 2.0 * M_PI;
    return a;
}

double HumanoidReferenceMPC::clamp(double v, double lo, double hi) {
    return std::max(lo, std::min(hi, v));
}

// ==================== HumanoidReferenceMPC Implementation ====================

HumanoidReferenceMPC::HumanoidReferenceMPC(const AcadosMPCParams& params)
    : params_(params)
    , capsule_(nullptr)
    , solver_initialized_(false)
{
#ifdef HAVE_ACADOS
    // Create acados solver capsule
    capsule_ = robot_mpc_acados_create_capsule();
    if (!capsule_) {
        std::cerr << "HumanoidReferenceMPC: Failed to create acados capsule\n";
        return;
    }
    
    // Create solver (allocate and initialize)
    int status = robot_mpc_acados_create(capsule_);
    if (status != 0) {
        std::cerr << "HumanoidReferenceMPC: acados_create failed with status " << status << "\n";
        robot_mpc_acados_free_capsule(capsule_);
        capsule_ = nullptr;
        return;
    }
    
    solver_initialized_ = true;
    std::cout << "HumanoidReferenceMPC: Acados solver initialized successfully.\n";
    std::cout << "  dt=" << params_.dt << ", N=" << params_.horizon << "\n";
#else
    std::cerr << "HumanoidReferenceMPC: Built without acados support (HAVE_ACADOS not defined)\n";
#endif
}

HumanoidReferenceMPC::~HumanoidReferenceMPC() {
#ifdef HAVE_ACADOS
    if (capsule_) {
        robot_mpc_acados_free(capsule_);
        robot_mpc_acados_free_capsule(capsule_);
    }
#endif
}

bool HumanoidReferenceMPC::computeControl(
    const AcadosMPCState& x0,
    const AcadosMPCState& x_goal,
    AcadosMPCControl& u_out)
{
    if (!solver_initialized_) {
        std::cerr << "HumanoidReferenceMPC: Solver not initialized\n";
        return false;
    }
    
#ifdef HAVE_ACADOS
    // Build reference trajectory
    AcadosMPCReference ref = buildReference(x0, x_goal);
    
    // Set initial state constraint
    setInitialState(x0);
    
    // Set stage and terminal references
    setReferences(ref);
    
    // Solve
    int status = robot_mpc_acados_solve(capsule_);
    if (status != 0) {
        std::cerr << "HumanoidReferenceMPC: Solve failed with status " << status << "\n";
        return false;
    }
    
    // Extract first control (acceleration)
    u_out = getFirstControl();
    
    // Debug: print what MPC computed
    static int debug_ctr = 0;
    if (debug_ctr++ % 50 == 0) {
        AcadosMPCVelocity v = getVelocityCommand();
        std::cout << "MPC output: vel=(" << v.vx << "," << v.vy << "," << v.omega 
                  << ") acc=(" << u_out.ax << "," << u_out.ay << "," << u_out.alpha << ")\n";
        std::cout << "  Ref[0]: pos=(" << ref.x_ref[0][0] << "," << ref.x_ref[0][1] << ") acc=(" 
                  << ref.u_ref[0][0] << "," << ref.u_ref[0][1] << ")\n";
        std::cout << "  x0: pos=(" << x0.px << "," << x0.py << ") vel=(" << x0.vx << "," << x0.vy << ")\n";
    }
    
    return true;
#else
    (void)x0; (void)x_goal; (void)u_out;
    return false;
#endif
}

bool HumanoidReferenceMPC::computeControlAndTrajectory(
    const AcadosMPCState& x0,
    const AcadosMPCState& x_goal,
    AcadosMPCControl& u_out,
    std::vector<AcadosMPCState>& predicted_states,
    std::vector<AcadosMPCControl>& predicted_controls)
{
    if (!computeControl(x0, x_goal, u_out)) {
        return false;
    }
    
    // Get predicted trajectory
    getPredictedTrajectory(predicted_states, predicted_controls);
    
    return true;
}

AcadosMPCReference HumanoidReferenceMPC::buildReference(
    const AcadosMPCState& x0,
    const AcadosMPCState& x_goal) const
{
    AcadosMPCReference ref;
    ref.x_ref.resize(params_.horizon + 1);
    ref.u_ref.resize(params_.horizon);
    
    // Goal in robot body frame
    const double dx_world = x_goal.px - x0.px;
    const double dy_world = x_goal.py - x0.py;
    const double dtheta = wrap_pi(x_goal.theta - x0.theta);
    
    // Transform goal to robot body frame (forward = x, sideways = y)
    const double cos_th0 = std::cos(x0.theta);
    const double sin_th0 = std::sin(x0.theta);
    const double dx_body = dx_world * cos_th0 + dy_world * sin_th0;
    const double dy_body = -dx_world * sin_th0 + dy_world * cos_th0;
    
    const double dp = std::hypot(dx_body, dy_body);
    
    // Time estimates
    const double vmax = params_.vx_max;
    const double time2target_xy = (dp > 1e-3) ? (dp / vmax) : 0.0;
    const double time2target_theta = (std::abs(dtheta) > 1e-3) ? 
                                      (std::abs(dtheta) / params_.omega_max) : 0.0;
    
    // Initialize state in robot local frame (starts at origin)
    double px = 0.0, py = 0.0, theta = 0.0;
    double vx = x0.vx, vy = x0.vy, omega = x0.omega;
    
    ref.x_ref[0] = {px, py, theta, vx, vy, omega};
    
    // Debug: print goal and time estimates
    static int ref_debug = 0;
    if (ref_debug++ % 50 == 0) {
        std::cout << "buildReference: goal_body=(" << dx_body << "," << dy_body << ") dp=" << dp 
                  << " time_xy=" << time2target_xy << " time_theta=" << time2target_theta << "\n";
    }
    
    // Build reference with bang-bang accelerations
    for (int k = 0; k < params_.horizon; ++k) {
        const double dx_rem = dx_body - px;
        const double dy_rem = dy_body - py;
        const double dtheta_rem = wrap_pi(dtheta - theta);
        
        // Bang-bang control selection
        double ax = 0.0, ay = 0.0, alpha = 0.0;
        
        // Rotation control
        if (std::abs(dtheta_rem) > 0.01) {
            alpha = (dtheta_rem > 0) ? params_.alpha_max : -params_.alpha_max;
        }
        
        // Position control strategy
        if (time2target_xy > time2target_theta) {
            // Position-limited: use forward AND sideways to reach goal
            if (std::abs(dx_rem) > 0.05) {
                ax = (dx_rem > 0) ? params_.ax_max : -params_.ax_max;
            }
            if (std::abs(dy_rem) > 0.05) {
                ay = (dy_rem > 0) ? params_.ay_max : -params_.ay_max;
            }
        } else {
            // Heading-limited: same - use both axes
            if (std::abs(dx_rem) > 0.05) {
                ax = (dx_rem > 0) ? params_.ax_max : -params_.ax_max;
            }
            if (std::abs(dy_rem) > 0.05) {
                ay = (dy_rem > 0) ? params_.ay_max : -params_.ay_max;
            }
        }
        
        ref.u_ref[k] = {ax, ay, alpha};
        
        // Integrate: x(k+1) = x(k) + v(k)*dt + 0.5*a*dt²
        const double dt = params_.dt;
        const double dt2 = 0.5 * dt * dt;
        
        // Update positions using CURRENT velocities
        px += vx * dt + ax * dt2;
        py += vy * dt + ay * dt2;
        theta = wrap_pi(theta + omega * dt + alpha * dt2);
        
        // Update velocities for next step - use conservative limits for reference
        vx = clamp(vx + ax * dt, -params_.vx_max * 0.90, params_.vx_max * 0.90);
        vy = clamp(vy + ay * dt, -params_.vy_max * 0.90, params_.vy_max * 0.90);
        omega = clamp(omega + alpha * dt, -params_.omega_max, params_.omega_max);
        
        ref.x_ref[k + 1] = {px, py, theta, vx, vy, omega};
    }
    
    return ref;
}

void HumanoidReferenceMPC::setInitialState(const AcadosMPCState& x0) {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    double x0_arr[6] = {x0.px, x0.py, x0.theta, x0.vx, x0.vy, x0.omega};
    ocp_nlp_constraints_model_set(capsule_->nlp_config, capsule_->nlp_dims, 
                                   capsule_->nlp_in, capsule_->nlp_out, 0, "lbx", x0_arr);
    ocp_nlp_constraints_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                                   capsule_->nlp_in, capsule_->nlp_out, 0, "ubx", x0_arr);
#else
    (void)x0;
#endif
}

void HumanoidReferenceMPC::setReferences(const AcadosMPCReference& ref) {
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    // Assuming LINEAR_LS cost with yref = [x; u] at stages and yref_e = [x] at terminal
    
    // Stage references
    for (int k = 0; k < params_.horizon; ++k) {
        double yref[9];  // [px, py, theta, vx, vy, omega, ax, ay, alpha]
        yref[0] = ref.x_ref[k][0];
        yref[1] = ref.x_ref[k][1];
        yref[2] = ref.x_ref[k][2];
        yref[3] = ref.x_ref[k][3];
        yref[4] = ref.x_ref[k][4];
        yref[5] = ref.x_ref[k][5];
        yref[6] = ref.u_ref[k][0];
        yref[7] = ref.u_ref[k][1];
        yref[8] = ref.u_ref[k][2];
        
        ocp_nlp_cost_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                               capsule_->nlp_in, k, "yref", yref);
    }
    
    // Terminal reference
    double yref_e[6];  // [px, py, theta, vx, vy, omega]
    yref_e[0] = ref.x_ref[params_.horizon][0];
    yref_e[1] = ref.x_ref[params_.horizon][1];
    yref_e[2] = ref.x_ref[params_.horizon][2];
    yref_e[3] = ref.x_ref[params_.horizon][3];
    yref_e[4] = ref.x_ref[params_.horizon][4];
    yref_e[5] = ref.x_ref[params_.horizon][5];
    
    ocp_nlp_cost_model_set(capsule_->nlp_config, capsule_->nlp_dims,
                           capsule_->nlp_in, params_.horizon, "yref", yref_e);
#else
    (void)ref;
#endif
}

AcadosMPCControl HumanoidReferenceMPC::getFirstControl() const {
    AcadosMPCControl control{0.0, 0.0, 0.0};
    
#ifdef HAVE_ACADOS
    if (!capsule_) return control;
    
    double u0[3];
    ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                    capsule_->nlp_out, 0, "u", u0);
    
    control.ax = u0[0];
    control.ay = u0[1];
    control.alpha = u0[2];
#endif
    
    return control;
}

void HumanoidReferenceMPC::getPredictedTrajectory(
    std::vector<AcadosMPCState>& states,
    std::vector<AcadosMPCControl>& controls) const
{
    states.resize(params_.horizon + 1);
    controls.resize(params_.horizon);
    
#ifdef HAVE_ACADOS
    if (!capsule_) return;
    
    // Extract states
    for (int k = 0; k <= params_.horizon; ++k) {
        double x[6];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, k, "x", x);
        
        states[k].px = x[0];
        states[k].py = x[1];
        states[k].theta = x[2];
        states[k].vx = x[3];
        states[k].vy = x[4];
        states[k].omega = x[5];
    }
    
    // Extract controls
    for (int k = 0; k < params_.horizon; ++k) {
        double u[3];
        ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                        capsule_->nlp_out, k, "u", u);
        
        controls[k].ax = u[0];
        controls[k].ay = u[1];
        controls[k].alpha = u[2];
    }
#endif
}

AcadosMPCVelocity HumanoidReferenceMPC::getVelocityCommand() const {
    AcadosMPCVelocity vel{0.0, 0.0, 0.0};
    
#ifdef HAVE_ACADOS
    if (!capsule_) return vel;
    
    // Get NEXT predicted state (after applying first control)
    // State 0 is the constrained initial state, state 1 is after integration
    double x1[6];
    ocp_nlp_out_get(capsule_->nlp_config, capsule_->nlp_dims,
                    capsule_->nlp_out, 1, "x", x1);
    
    vel.vx = x1[3];
    vel.vy = x1[4];
    vel.omega = x1[5];
#endif
    
    return vel;
}

} // namespace setpoint
} // namespace spg
